### ISSUE TITLE
which corpus do you use in the training phase?

### ISSUE THREAD

**Issue by wangsssky** [gy910210/spelling-corrector#1]
I found that the data in the final.out file is not sufficient.  May I know which corpus you use in the training phase?

**Comment by pangolulu** [comment]
Data for training the model only depend on the ''(true word, spelling word)'' pairs, or some position information. I think final.out is sufficient enough. The data come from the true IME.

**Comment by gy910210** [comment]
Data for training the model only depend on the ''(true word, spelling word)'' pairs, or some position information. I think final.out is sufficient enough. The data come from the true IME.
